name: pipeline deployment
on:
  push:
    branches:
      - master

jobs: 
  simple_deployment:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '16'
      - name: Install packages
        run: npm i
      - name: lint
        run: npm run eslint
      - name: test
        run: npm run test
      - name: Running cypress
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
